<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documentation<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <a href="{genUrl controller="static" action="switches"}">Connecting Switches</a>
            <a href="{genUrl controller="static" action="port-security"}">Port Security Policies</a>
            <a href="{genUrl controller="static" action="route-servers"}">Route Servers</a>
        </li>

        {* PLEASE LEAVE THIS SOMEWHERE!  IT'S ONLY FAIR INEX GETS SOME CREDIT :D *}
        <li class="divider"></li>
        <li>
            <a href="{genUrl controller="index" action="about"}">About</a>
        </li>
    </ul>
</li>
