
Dear New SIX Member,

Firstly, welcome to {$options.identity.orgname}! This is your {$options.identity.name} welcome e-mail.

Please take some time to read this email -- it contains important information concerning your {$options.identity.orgname} membership.

Several sections of this email require your input; these are all clearly marked by the heading "Your Input".  We would appreciate if you could provide us with all the details requested as this will allow us to provide you and other {$options.identity.orgname} members with a better quality of service.


Connection Details
==================

You have opted to connect to {$options.identity.orgname} using {$customer->getVirtualInterfaces()|@count} Ethernet ports.

Unless you have been advised otherwise, you have been assigned an untagged port on the primary peering LAN(s).

We have assigned the following IP addresses and switch-ports for your exclusive use:

{foreach $customer->getVirtualInterfaces() as $connection}
============================================
Connection {counter name=numconnections}
============================================

LAG Port:        {if $connection->getPhysicalinterfaces()|@count > 1}Yes, comprising of:{else}No{/if}

{foreach $connection->getPhysicalinterfaces() as $pi}
Switch Port:     {$pi->getSwitchPort()->getSwitcher()->getName()}.arnes.si, {$pi->getSwitchPort()->getName()}
Speed:           {$pi->getSpeed()}Mbps
Duplex:          {$pi->getDuplex()}
Location:        {$pi->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}

{/foreach}

{foreach $connection->getVlanInterfaces() as $vi}
{$vlanid = $vi->getVlan()->getId()}
{$vi->getVlan()->getName()}
---------------------------------------------

{if $vi->getIpv6enabled()}
IPv6 Address:  {$vi->getIPv6Address()->getAddress()}/{$netinfo.$vlanid.6.masklen}
IPv6 Hostname: {$vi->getIpv6hostname()}
{else}
IPv6:          Please contact us at {$options.identity.email} to enable IPv6
{/if}

{if $vi->getIpv4enabled()}
IPv4 Address:  {$vi->getIPv4Address()->getAddress()}/{$netinfo.$vlanid.4.masklen}
IPv4 Hostname: {$vi->getIpv4hostname()}
{else}
IPv4:          Please contact us at {$options.identity.email} to enable IPv4
{/if}

{if not isset( $ipv4md5 )}
    {assign var='ipv4md5' value=$vi->getIpv4bgpmd5secret()}
    {assign var='ipv6md5' value=$vi->getIpv6bgpmd5secret()}
{/if}

{/foreach}

{/foreach}

Your Input
----------

Should you require your reverse DNS hostnames changed for either IPv4 or IPv6, please contact {$options.identity.email}.


Member Portal :: IXP Manager
============================

{$options.identity.orgname} provides a portal for members which provides traffic graphs for your ports, the ability to self-provision some services, the contact and peering details of all other members, documentation, support information and much more.

Every member is assigned an Administration account with which you then create individual user accounts. The Administration account is only meant for this purpose and as such, all functionality is only available through user accounts.

{if $admins|@count}
We have created your administration account(s) with the following username(s) and email address(es):

{foreach $admins as $a}
  * {$a->getUsername()} <{$a->getEmail()}>
{/foreach}

Please browse to the following page and use the 'Lost Password' facility to set a new password for this account.

{genUrl controller="auth" action="lost-password"}
{else}
Please contact us for your account details at {$options.identity.email}.
{/if}



Route Servers
=============

{$options.identity.orgname} operates a Route Server cluster; this facility allows all members who connect to the cluster to see all routing prefixes sent to the cluster by any other member.  I.e. it provides an quick, safe and easy way to peer with any other route server user.

The {$options.identity.orgname} route server cluster is aimed at:

o  small to medium sized members of the exchange who don't have the time or resources to aggressively manage their peering relationships.

o  larger members of the exchange who have an open peering policy, but where it may not be worth their while managing peering relationships with smaller members of the exchange.

If you don't have any good reasons not to use the route server cluster, you should probably use it.

The service is designed to be reliable. It operates on two physical servers, each located in a different data centre.  The route servers filter inbound routing prefixes based on published RIPE IRR policies, which means that using the route servers for peering is generally much safer than peering directly with other members.

See {genUrl controller="dashboard" action="rs-info"} for more information.


Mailing Lists
=============

To encourage co-operation between {$options.identity.orgname} members, {$options.identity.orgname} provides provides a private mailing list service at six-apm@arnes.si.


Your Input
----------

Please contact SIX operations ({$options.identity.email}) with an email address you wish to subscribe to the mailing list. This is usually a mailing list itself, such as noc@<your_domain>. Please let us know of any other From addresses you will be sending from as well.

----------


SIX Operations
===============

Technical Operations for SIX are provided by Arnes. Technical support contact details for SIX can be found at:

        {genUrl controller="static" action="support"}

In general, the best way to contact SIX operations is by email at: {$options.identity.email}.  If there is an emergency requiring immediate assistance, please contact the on call engineer via the mobile number: +386 41 793 060.


Peering
=======

Arnes facilitates peering between SIX members, but does not mandate peering with any particular member. Users are encouraged to peer with route servers (see above), however bilateral peerings are also permitted.

You will find a full list of members on the IXP Manager, along with the correct email addresses to use for peering requests.

When emailing other SIX members about peering requests, please include all technical details relevant to the peering session, including your IP address, your AS number, and an estimate of the number of prefixes you intend to announce to that candidate peer.


NOC Details
===========

For the convenience of its members, SIX maintains a list of NOC and peering contact details for its members.  These details are held on a private SIX database, and are available only from the IXP Manager on the following URL:

        {genUrl controller="customer" action="details"}

This area of the SIX website is password protected and SSL secured. Passwords are only provided to current SIX members.  This information is considered private and will not be passed on to other third parties by Arnes.

We would appreciate if you could take the time to ensure that the following details we hold on file are correct:

Your Input
----------

Member name:                    {$customer->getName()}
Primary corporate web page:     {$customer->getCorpwww()}
Peering Email Address:          {$customer->getPeeringemail()}
NOC Phone number:               {$customer->getNocphone()}
NOC Fax number:                 {$customer->getNocfax()}
General NOC email address:      {$customer->getNocemail()}
NOC Hours:                      {$customer->getNochours()}
Dedicated NOC web page:         {$customer->getNocwww()}
AS Number:                      {$customer->getAutsys()}

----------


Router Configuration
====================

If you are new to internet exchanges, we would ask you to note that all members are expected to adhere to the technical requirements on the SIX website.  In particular, we would draw your attention to section of these requirements which outline what types of traffic may and may not be forwarded to the SIX peering LAN.

For Cisco IOS based routers, we recommend the following interface configuration commands:

 no ip redirects
 no ip proxy-arp
 no ip directed-broadcast
 no mop enabled
 no cdp enable
 udld port disable

If you intend to use IPv6 with a Cisco IOS based router, please also consider the following interface commands:

 no ipv6 redirects
 ipv6 nd suppress-ra

For further details please see the following URL:

        http://www.arnes.si/six-sticisce-omrezij/pogoji-clanstva.html (in Slovene)
        http://www.arnes.si/en/infrastructure/six-internet-exchange/technical-and-administrative-requirements.html (in English)


Connecting Switches to SIX
==========================

Many members choose to connect their SIX port to a layer 2 switch and then forward their peering traffic to a router virtual interface hosted elsewhere on their network.  While connecting layer 2 switches to the SIX peering LAN is not actively discouraged, incorrect configuration can cause serious and unexpected connectivity problems.

The primary concern is to ensure that only traffic from the router subinterface is presented to the SIX port. SIX implements per port mac address counting: if more than 1 mac address is seen on any switch port at any time, that port will automatically be disabled for a cooling off period, and your connectivity to SIX will temporarily be lost.

This policy prevents two potential problems: firstly, it ensures that layer 2 traffic loops are prevented and secondly, it ensures that no other traffic escapes to the SIX peering LAN which shouldn't be seen there.

If you choose to connect your SIX port or ports to a switch, it is critically important to assign one unique vlan for each SIX connection.  If you share an SIX facing VLAN between multiple SIX ports or share a SIX-facing VLAN with any other network, your connection will automatically be shut down due to the security mechanisms implemented by SIX.

Please also note that by default, several switch models send link-local traffic to all ports.  On Cisco switches, this can be disabled using the following interface commands:

interface GigabitEthernetx/x
 spanning-tree bpdufilter enable
 no keepalive
 no cdp enable
 udld port disable

For further details please see the following URL:

        {genUrl controller="static" action="switches"}


Monitoring
==========

By default, SIX actively monitors all ports on its peering LANs using ICMP PING for both connectivity and host latency.  This monitoring causes about 25 PING packets to be sent to each IP address on the peering LAN every 5 minutes.  If you do not wish for your router to be actively monitored, please mail {$options.identity.email} and we can disable this facility.


PeeringDB
=========

PeeringDB ( http://www.peeringdb.com/ ) facilitates the exchange of information related to peering. Specifically, what networks are peering, where they are peering, and if they are likely to peer with you.

More and more organisations are using PeeringDB to make decisions on where they should open POPs, provision new links, etc.

We would very much appreciate it if you could mark your new SIX peering under the "Public Peering Locations" section of your PeeringDB page. We are listed as 'SIX SI'. If you do not yet have a PeeringDB account, we would suggest that you register for one on their site.


Welcome to SIX, Slovenian Internet eXchange.


SIX Operations


