{tmplinclude file="header.phtml"}

{if isset( $user ) and $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            Documentation <span class="divider">/</span>
        </li>
        <li class="active">
            Technical Support and Contact Information
        </li>
    </ul>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>Technical Support</h1>
        </div>
{/if}

<p>
Regular technical support at SIX is provided on an office hours basis from 08:00 to 16:00 CET,
Monday through Friday. The normal communications channel for technical support is email to
<a href="mailto:noc@six.si">noc@six.si</a>. SIX operations staff are available by 
telephone on +386 1 479 8800.
</p>
<p>
A 24-hour advance notice is required to access SIX facilities during normal office hours.
</p>

<h3>Emergency 24x7x365 Support</h3>

<p>
An 24-hour support line is available on +386 41 793 060 for emergency
calls which fall outside normal office hours. This support facility is intended for emergencies
only, including:
</p>

<ul>
    <li> SIX critical system failures causing loss of service to members </li>
    <li> Emergency out-of-hours access to SIX cages for members who house routers there </li>
</ul>


<h3>Support Summary</h3>

<table border="0">
<tr>
    <td width="20"></td>
    <td align="right"><strong>Email:</strong></td>
    <td width="10"></td>
    <td align="left"><a href="mailto:noc@six.si">noc@six.si</a></td>
</tr>
<tr>
    <td></td>
    <td align="right"><strong>Phone:</strong></td>
    <td></td>
    <td align="left">+386 1 479 8800</td>
</tr>
<tr>
    <td></td>
    <td align="right"><strong>Hours:</strong></td>
    <td></td>
    <td align="left">08:00 to 16:00 CET, Monday to Friday</td>
</tr>
<tr>
    <td></td>
    <td align="right"><strong>24h Emergency:</strong></td>
    <td></td>
    <td align="left">+386 41 793 060</td>
</tr>
</table>


{if not isset( $user ) or $user->getPrivs() neq 3}
    </div>
{/if}

{tmplinclude file="footer.phtml"}

